name: Laravel Tests

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: gd, pdo, pgsql

    - name: Copy .env.testing
      run: cp .env.example .env.testing

    - name: Install dependencies
      run: composer install

    - name: Generate application key
      run: php artisan key:generate --env=testing

    - name: Run tests
      run: php artisan test

